import{a as f,S as m}from"./assets/vendor-CwMn2xmy.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const y="46669299-ebb68efeed7427af4171916f3",g="https://pixabay.com/api/",b=45,w=async(s,t=1,r=15)=>{const n=b-(t-1)*r;if(n<=0)return{hits:[],totalHits:0};r=Math.min(r,n);const e=`${g}?key=${y}&q=${encodeURIComponent(s)}&image_type=photo&orientation=horizontal&safesearch=true&page=${t}&per_page=${r}`;try{return(await f.get(e)).data}catch{throw new Error("Помилка завантаження зображень")}},L=s=>{const t=document.querySelector(".list-photos"),r=s.map(e=>`
        <li>
            <a href="${e.largeImageURL}">
                <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
            </a>
            <div>
                <p>Likes: ${e.likes}</p>
                <p>Views: ${e.views}</p>
                <p>Comments: ${e.comments}</p>
                <p>Downloads: ${e.downloads}</p>
            </div>
        </li>
    `).join("");t.insertAdjacentHTML("beforeend",r),new m(".list-photos a").refresh()},v=document.getElementById("search-form"),d=document.getElementById("search-field"),i=document.getElementById("load-more"),E=document.querySelector(".list-photos"),c=document.createElement("div");c.textContent="Завантаження...";c.classList.add("loading-indicator");let l=1,h="",u=0,I=new m(".list-photos a");v.addEventListener("submit",async s=>{s.preventDefault();const t=d.value.trim();t&&(l=1,h=t,E.innerHTML="",i.style.display="none",await p(t),d.value="")});i.addEventListener("click",async()=>{l+=1,await p(h)});async function p(s){document.body.appendChild(c);try{const t=await w(s,l),r=t.hits;if(u=t.totalHits,r.length===0&&l===1){showNoResultsMessage();return}L(r),I.refresh();const n=document.querySelectorAll(".list-photos img").length;n>=u||n>=45?(i.style.display="none",$()):i.style.display="block";const e=document.querySelector(".list-photos li").getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}catch(t){console.error(t)}finally{c.remove()}}function $(){const s=document.createElement("p");s.textContent="We're sorry, but you've reached the end of search results.",s.classList.add("end-of-results-message"),document.body.appendChild(s)}
//# sourceMappingURL=index.js.map
