import{a as p,S as h}from"./assets/vendor-CwMn2xmy.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const y="46669299-ebb68efeed7427af4171916f3",g="https://pixabay.com/api/",L=async(o,t=1,n=15)=>{const s=`${g}?key=${y}&q=${encodeURIComponent(o)}&image_type=photo&orientation=horizontal&safesearch=true&page=${t}&per_page=${n}`;try{return(await p.get(s)).data}catch{throw new Error("Помилка завантаження зображень")}},w=o=>{const t=document.querySelector(".list-photos"),n=o.map(s=>`
        <li>
            <a href="${s.largeImageURL}">
                <img src="${s.webformatURL}" alt="${s.tags}" loading="lazy" />
            </a>
            <div>
                <p>Likes: ${s.likes}</p>
                <p>Views: ${s.views}</p>
                <p>Comments: ${s.comments}</p>
                <p>Downloads: ${s.downloads}</p>
            </div>
        </li>
    `).join("");t.insertAdjacentHTML("beforeend",n)},b=document.getElementById("search-form"),d=document.getElementById("search-field"),c=document.getElementById("load-more"),v=document.querySelector(".list-photos"),a=document.createElement("div");a.textContent="Завантаження...";a.classList.add("loading-indicator");let i=1,m="",u=0;const E=15;let I=new h(".list-photos a");b.addEventListener("submit",async o=>{o.preventDefault();const t=d.value.trim();t&&(i=1,m=t,v.innerHTML="",c.style.display="none",S(),await f(t),d.value="")});c.addEventListener("click",async()=>{i+=1,await f(m)});async function f(o){document.body.appendChild(a);try{const t=await L(o,i,E),n=t.hits;if(u=t.totalHits,n.length===0&&i===1){q();return}if(w(n),I.refresh(),document.querySelectorAll(".list-photos img").length>=u?(c.style.display="none",$()):c.style.display="block",i>1){const e=document.querySelector(".list-photos li").getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}}catch(t){console.error(t)}finally{a.remove()}}function $(){if(!document.querySelector(".end-of-results-message")){const o=document.createElement("p");o.textContent="We're sorry, but you've reached the end of search results.",o.classList.add("end-of-results-message"),document.body.appendChild(o)}}function S(){const o=document.querySelector(".end-of-results-message");o&&o.remove()}function q(){iziToast.info({title:"No results",message:"No images found for your search query."})}
//# sourceMappingURL=index.js.map
